apiVersion: v1
kind: Service
metadata:
  name: ms-storage-service
spec:
  selector:
    app: ms-storage
  ports:
    # service will be vailable at localhost:5001
    - port: 5001
      targetPort: 5000
  type: LoadBalancer
