version: "3.6"

services:
  storage_integrationtests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - Storage__ConnectionString=mongodb://mongoserver:27017
    depends_on: 
      - mongoserver
  
  mongoserver:
    image: mongo
    ports:
      - 27017:27017
