FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS restore
WORKDIR /app
COPY . .
RUN dotnet restore

FROM restore as publish
WORKDIR /app
RUN dotnet publish --configuration Release --no-restore

FROM publish as test
WORKDIR /app/Nokia.Storage.IntegrationTest

CMD dotnet test