apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    # will select all pods by mongodb
    app: mongodb
  ports:
    - protocol: TCP
      # Port accessible inside cluster
      port: 27017
      # Port to forward to inside the pod
      targetPort: 27017
  type: ClusterIP